Iter19
den14-dn/go-shortener-url pull request #19
Opened 2023-10-18 21:11 UTC by den14-dn

2023-10-20 20:51 UTC, valentinsoe requested changes
Спасибо за работу!

В работе не хватает документации к статическому анализатору.

2023-10-20 20:51 UTC, valentinsoe commented on pkg/osexitcheckanalyzer/osexitcheckanalyzer.go
> +	expr := func(x *ast.ExprStmt) bool {
Занудство. Название переменной не самое удачное. Не прочитав код - не понять что за expr.
isOsExit было бы лучше

2023-10-21 08:50 UTC, den14-dn commented on pkg/osexitcheckanalyzer/osexitcheckanalyzer.go
> +	expr := func(x *ast.ExprStmt) bool {
Спасибо за рекомендацию, переменную переименовал от общего названия к самоописанию.

2023-10-23 06:15 UTC, valentinsoe approved these changes
Спасибо за исправления. Работу принимаю!

2023-10-25 19:13 UTC, merged