Iter22
den14-dn/go-shortener-url pull request #22
Opened 2023-10-29 20:51 UTC by den14-dn

2023-10-31 00:48 UTC, valentinsoe requested changes
Спасибо за работу!
К тому  что сделано в данном спринте замечаний нет.

Но gracefull shutdown не учитывает вот эти горутины удаления ссылок:
https://github.com/den14-dn/go-shortener-url/blob/iter22/internal/controller/handlers.go#L344C3-L344C34

2023-11-07 00:19 UTC, valentinsoe requested changes
Спасибо за доработки.
Но после закрытия канала надо дождаться выполнения горутин-воркеров.
Иначе какие-то операции могут быть прерваны на середине, какие-то ссылки к удалению могут быть не удалены.

2023-11-07 00:19 UTC, valentinsoe commented on internal/pkg/deleteurl/deleteurl.go
> +	close(d.chJob)
Таким образом мы не дождемся завершения горутин "воркеров".
А сразу вернем управление вызывающему. И если в канале есть задачи они будут утеряны.

2023-11-07 00:19 UTC, valentinsoe commented on internal/pkg/deleteurl/deleteurl.go
> +		if err := d.storage.Delete(ctx, j.url); err != nil {
При закрытии канала, если до сюда дойдет управление - будет попытка удалить пустой урл(пустую строку)

2023-11-07 11:15 UTC, valentinsoe requested changes
Спасибо за исправления.
Но go deleter.Run(...) во-первых не нужен, во-вторых может приводить к "гонкам"

2023-11-07 11:15 UTC, valentinsoe commented on internal/controller/handlers_test.go
> +	go deleter.Run(1)
И если в main запуск горутины тебя не подводит, то тут вполне может.
Если почитать внимательно ошибки в тестах там все написано. У нас нет гарантий что мы не начнем ждать завершения вейтгруппы до вызова wg.Add. Что достаточно хитрый go test обнаруживает и справедливо считает гонкой.

2023-11-07 15:55 UTC, den14-dn commented on internal/app/app.go
> +	go deleterURLs.Run(workersDeletingURLs)
Изначально сделал go deleter.Run(...) чтобы запустить поток, который поднимет нужное количество воркеров, потом встанет на ожидания завершения всех воркеров. Но уже вижу, что действительно Run(...) тут не нужен.

2023-11-07 16:23 UTC, den14-dn commented on internal/pkg/deleteurl/deleteurl.go
> +		if err := d.storage.Delete(ctx, j.url); err != nil {
Не очень понимаю описываемой тут ситуации, точнее в какой момент она возможна?
Делал тестовый код:
 - сделал объект задания;
 - создал буферизованный канал;
 - запустил воркеры, слушающие канал с заданиями;
 - наполнил канал заданиями (количество заданий больше размера буфера);
 - закрыл канал, стал на ожидание завершения воркеров;
 - каждый воркер прочитал все из канала, через fmt.Println вывел поля задания и завершился.

В данном кейсе нет случая чтобы при закрытии канала поля задания были начального значения.

2023-11-07 19:31 UTC, valentinsoe approved these changes
Продано! То есть принято!

2023-11-08 07:31 UTC, merged